<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>4.1.1</version>
		<relativePath/> <!-- lookup parent from repository -->
	</parent>

	<groupId>org.eu.liaohongdong.eShop</groupId>
	<artifactId>eShop</artifactId>
	<version>1.0-SNAPSHOT</version>
	<packaging>pom</packaging>
	<modules>
		<module>eShop-common</module>
		<module>eShop-mpg</module>
	</modules>

	<properties>
		<java.version>17</java.version>
		<skipTests>true</skipTests>
		<druid.version>1.2.28</druid.version>
		<hutool.version>5.8.40</hutool.version>
		<springdoc-openapi.version>3.1.1</springdoc-openapi.version>
		<mybatis-plus.version>3.5.17</mybatis-plus.version>
		<velocity-engine-core.version>2.4.1</velocity-engine-core.version>
		<mysql-connector.version>9.7.0</mysql-connector.version>
		<logstash-logback.version>9.0</logstash-logback.version>
		<spring-data-commons.version>4.1.1</spring-data-commons.version>
		<okhttp3.version>5.5.0</okhttp3.version>
		<commons-lang3.version>3.20.0</commons-lang3.version>
		<bouncycastle.version>1.86</bouncycastle.version>
	</properties>

	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-actuator</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-aspectj</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>cn.hutool</groupId>
			<artifactId>hutool-all</artifactId>
		</dependency>
		<dependency>
			<groupId>org.projectlombok</groupId>
			<artifactId>lombok</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-configuration-processor</artifactId>
			<optional>true</optional>
		</dependency>
	</dependencies>

	<dependencyManagement>
		<dependencies>
			<!-- 统一管理版本，子模块引用时无需再写 version-->
			<dependency>
				<groupId>org.eu.liaohongdong.eShop</groupId>
				<artifactId>eShop-common</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>org.eu.liaohongdong.eShop</groupId>
				<artifactId>eShop-mbg</artifactId>
				<version>${project.version}</version>
			</dependency>
			<!--集成druid连接池-->
			<dependency>
				<groupId>com.alibaba</groupId>
				<artifactId>druid-spring-boot-4-starter</artifactId>
				<version>${druid.version}</version>
			</dependency>
			<!--Hutool Java工具包-->
			<dependency>
				<groupId>cn.hutool</groupId>
				<artifactId>hutool-all</artifactId>
				<version>${hutool.version}</version>
			</dependency>
			<!--SpringDoc相关依赖-->
			<dependency>
				<groupId>org.springdoc</groupId>
				<artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>
				<version>${springdoc-openapi.version}</version>
			</dependency>
			<!--MyBatis-Plus的Starter依赖-->
			<dependency>
				<groupId>com.baomidou</groupId>
				<artifactId>mybatis-plus-spring-boot4-starter</artifactId>
				<version>${mybatis-plus.version}</version>
			</dependency>
			<!-- MyBatis-Plus-->
			<dependency>
				<groupId>com.baomidou</groupId>
				<artifactId>mybatis-plus</artifactId>
				<version>${mybatis-plus.version}</version>
			</dependency>
			<!-- MyBatis-Plus 代码生成器-->
			<dependency>
				<groupId>com.baomidou</groupId>
				<artifactId>mybatis-plus-generator</artifactId>
				<version>${mybatis-plus.version}</version>
			</dependency>
			<!-- 模板引擎 velocity，生成代码用 -->
			<dependency>
				<groupId>org.apache.velocity</groupId>
				<artifactId>velocity-engine-core</artifactId>
				<version>${velocity-engine-core.version}</version>
			</dependency>
			<!--Mysql数据库驱动-->
			<dependency>
				<groupId>com.mysql</groupId>
				<artifactId>mysql-connector-j</artifactId>
				<version>${mysql-connector.version}</version>
			</dependency>
			<!--SpringData工具包-->
			<dependency>
				<groupId>org.springframework.data</groupId>
				<artifactId>spring-data-commons</artifactId>
				<version>${spring-data-commons.version}</version>
			</dependency>
			<!--集成logstash-->
			<dependency>
				<groupId>net.logstash.logback</groupId>
				<artifactId>logstash-logback-encoder</artifactId>
				<version>${logstash-logback.version}</version>
			</dependency>
			<!--Apache Commons Lang3-->
			<dependency>
				<groupId>org.apache.commons</groupId>
				<artifactId>commons-lang3</artifactId>
				<version>${commons-lang3.version}</version>
			</dependency>
			<!--Bouncy Castle加密库-->
			<dependency>
				<groupId>org.bouncycastle</groupId>
				<artifactId>bcprov-jdk18on</artifactId>
				<version>${bouncycastle.version}</version>
			</dependency>
			<!--OkHttp JVM-->
			<dependency>
				<groupId>com.squareup.okhttp3</groupId>
				<artifactId>okhttp-jvm</artifactId>
				<version>${okhttp3.version}</version>
			</dependency>
		</dependencies>
	</dependencyManagement>

	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<configuration>
					<compilerArgs>
						<arg>-parameters</arg>
					</compilerArgs>
				</configuration>
			</plugin>
		</plugins>
	</build>

	<repositories>
		<repository>
			<id>aliyunmaven</id>
			<name>aliyun</name>
			<url>https://maven.aliyun.com/repository/public</url>
		</repository>
	</repositories>

	<pluginRepositories>
		<pluginRepository>
			<id>aliyunmaven</id>
			<name>aliyun</name>
			<url>https://maven.aliyun.com/repository/public</url>
		</pluginRepository>
	</pluginRepositories>

</project>